server.port=8080
<<<<<<< HEAD

## B?t ghi log cho package service
#logging.level.com.example.loggingdemo.service=trace


# 1. Level toàn c?c & c?p package
logging.level.root=INFO
logging.level.com.example.loggingdemo.service=WARN
logging.level.com.example.loggingdemo.controller=WARN

# 2. Xu?t Log ra File
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB

# 3. ??nh d?ng Pattern Console
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


=======
spring.application.name=spring-boot-logging-demo
>>>>>>> 0c93dd3
