server.port=8080

## B?t ghi log cho package service
#logging.level.com.example.loggingdemo.service=trace

# ERROR > WARN > INFO > DEBUG > TRACE
# 1. Level toàn c?c & c?p package
logging.level.root=INFO
logging.level.com.example.loggingdemo.service=TRACE
#logging.level.com.example.loggingdemo.controller=WARN

# 2. Xu?t Log ra File
#logging.file.name=logs/application.log
#logging.logback.rollingpolicy.max-file-size=10MB

# 3. ??nh d?ng Pattern Console
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#LOGBACK
# quét các c?u hình theo tên :
#logback.xml, logback-spring.xml , logback.groovy, logback-spring.groovy


